name: Rebuild and Publish PDF
on: 
  push:
    tags:
      - v**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Ubuntu packages
        run: |
          sudo apt-get install python3-sympy texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-science
      - name: Build PDF
        run: |
          make publish
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: riscv-debug-stable.pdf
