name: Rebuild and Publish PDF
on:
  push:
    branch:
      - 'v[0-9].[0-9]*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Ubuntu packages
        run: |
          sudo apt-get install python3-sympy texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-science
      - name: Build PDF
        run: |
          make all
      - name: Draft
        uses: softprops/action-gh-release@v1
        if: contains(github.ref, 'draft')
        with:
          files: riscv-debug-draft.pdf
      - name: Stable
        uses: softprops/action-gh-release@v1
        if: contains(github.ref, 'stable')
        with:
          files: riscv-debug-stable.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: contains(github.ref, 'release')
        with:
          files: riscv-debug-release.pdf

